image:
  repository: henria/weather_app_frontend
  tag: "59314c00528d9fee4bd2547065b7e98ebde57a51"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

env:
  - name: BACKEND_URL
    value: "http://weather-backend-weather-backend:80"
  - name: FLASK_ENV
    value: development
