image:
  repository: henria/weather_app_frontend
  tag: "latest"   # auto-updated by GitHub Actions on semver git tag (e.g. v1.2.3)
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

env:
  - name: BACKEND_URL
    value: "http://weather-backend-weather-backend:80"
  - name: FLASK_ENV
    value: production
