image:
  repository: henria/weather_app_backend
  tag: "latest"   # auto-updated by GitHub Actions on semver git tag (e.g. v1.2.3)
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  - name: FLASK_ENV
    value: production
