image:
  repository: henria/weather_app_backend
  tag: "8ee888f08e70031bec731eeb1ed7ed6b4515c1dc"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  - name: FLASK_ENV
    value: development
